import type { CapabilityDefinition } from "@/lib/capability-registry/capability-contract";

const WEB_MOBILE: CapabilityDefinition["supportedPlatforms"] = ["web", "ios", "android", "desktop"];

function cap(
  partial: Omit<CapabilityDefinition, "availability"> & { availability?: CapabilityDefinition["availability"] },
): CapabilityDefinition {
  return {
    availability: "available",
    ...partial,
  };
}

/** Canonical capability catalog — providers listed by priority (desc) per capability. */
export const CAPABILITY_CATALOG: Record<CapabilityDefinition["id"], CapabilityDefinition> = {
  NAVIGATE: cap({
    id: "NAVIGATE",
    name: "Navigate",
    description: "Open navigation to a destination",
    category: "mobility",
    priority: "high",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "destination", label: "Destination", required: true }] },
    outputSchema: { kind: "url" },
    providers: [
      { id: "kakao_navi", name: "Kakao Navi", platforms: WEB_MOBILE, priority: 90 },
      { id: "naver_map", name: "Naver Map", platforms: WEB_MOBILE, priority: 80 },
      { id: "google_maps", name: "Google Maps", platforms: WEB_MOBILE, priority: 70 },
      { id: "internal_navigation", name: "Rimvio Navigation", platforms: WEB_MOBILE, priority: 60 },
    ],
  }),
  CALL: cap({
    id: "CALL",
    name: "Call",
    description: "Place a phone call",
    category: "communication",
    priority: "high",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "phone", label: "Phone number" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "tel_default", name: "Phone dialer", platforms: WEB_MOBILE, priority: 100 }],
  }),
  MESSAGE: cap({
    id: "MESSAGE",
    name: "Message",
    description: "Send a message",
    category: "communication",
    priority: "normal",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: {
      fields: [
        { key: "phone", label: "Recipient" },
        { key: "body", label: "Message body" },
      ],
    },
    outputSchema: { kind: "url" },
    providers: [
      { id: "kakao_talk", name: "KakaoTalk", platforms: WEB_MOBILE, priority: 90 },
      { id: "sms_default", name: "SMS", platforms: WEB_MOBILE, priority: 70 },
    ],
  }),
  ALARM: cap({
    id: "ALARM",
    name: "Alarm",
    description: "Set a reminder or alarm",
    category: "productivity",
    priority: "high",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Reminder title", required: true }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "system_alarm", name: "Rimvio Alarm", platforms: WEB_MOBILE, priority: 100 }],
  }),
  EMAIL: cap({
    id: "EMAIL",
    name: "Email",
    description: "Compose an email",
    category: "communication",
    priority: "normal",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: {
      fields: [
        { key: "to", label: "Recipient" },
        { key: "subject", label: "Subject" },
      ],
    },
    outputSchema: { kind: "url" },
    providers: [{ id: "mailto_default", name: "Mail composer", platforms: WEB_MOBILE, priority: 100 }],
  }),
  CALENDAR: cap({
    id: "CALENDAR",
    name: "Calendar",
    description: "View or confirm a schedule",
    category: "productivity",
    priority: "high",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Event title" }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_calendar", name: "Rimvio Calendar", platforms: WEB_MOBILE, priority: 100 }],
  }),
  PARKING: cap({
    id: "PARKING",
    name: "Parking",
    description: "Find or pay for parking",
    category: "mobility",
    priority: "normal",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "place", label: "Place name" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "kakao_parking", name: "Kakao Parking", platforms: WEB_MOBILE, priority: 100 }],
  }),
  TAXI: cap({
    id: "TAXI",
    name: "Taxi",
    description: "Call a taxi",
    category: "mobility",
    priority: "high",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "destination", label: "Destination" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "kakao_taxi", name: "Kakao T", platforms: WEB_MOBILE, priority: 100 }],
  }),
  SEARCH: cap({
    id: "SEARCH",
    name: "Search",
    description: "Search the web for context",
    category: "productivity",
    priority: "normal",
    executionMode: "web",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "query", label: "Search query", required: true }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "google_search", name: "Web search", platforms: WEB_MOBILE, priority: 100 }],
  }),
  DOCUMENT: cap({
    id: "DOCUMENT",
    name: "Document",
    description: "Open or create a document",
    category: "productivity",
    priority: "low",
    executionMode: "web",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Document title" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "google_docs", name: "Google Docs", platforms: WEB_MOBILE, priority: 100 }],
  }),
  SHEET: cap({
    id: "SHEET",
    name: "Sheet",
    description: "Open a spreadsheet",
    category: "productivity",
    priority: "low",
    executionMode: "web",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Sheet title" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "google_sheets", name: "Google Sheets", platforms: WEB_MOBILE, priority: 100 }],
  }),
  LINK: cap({
    id: "LINK",
    name: "Link",
    description: "Open a related link",
    category: "system",
    priority: "low",
    executionMode: "web",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "url", label: "URL" }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "rimvio_link", name: "Rimvio Link", platforms: WEB_MOBILE, priority: 100 }],
  }),
  MAP: cap({
    id: "MAP",
    name: "Map",
    description: "Open map for a place",
    category: "mobility",
    priority: "normal",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "place", label: "Place", required: true }] },
    outputSchema: { kind: "url" },
    providers: [
      { id: "naver_map", name: "Naver Map", platforms: WEB_MOBILE, priority: 90 },
      { id: "kakao_navi", name: "Kakao Map", platforms: WEB_MOBILE, priority: 85 },
    ],
  }),
  BOOK_FLIGHT: cap({
    id: "BOOK_FLIGHT",
    name: "Book flight",
    description: "Reserve or confirm flights",
    category: "travel",
    priority: "critical",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Trip title" }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_flight", name: "Rimvio Flight", platforms: WEB_MOBILE, priority: 100 }],
  }),
  BOOK_HOTEL: cap({
    id: "BOOK_HOTEL",
    name: "Book hotel",
    description: "Reserve accommodation",
    category: "travel",
    priority: "critical",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Stay title" }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_hotel", name: "Rimvio Hotel", platforms: WEB_MOBILE, priority: 100 }],
  }),
  CHECK_IN: cap({
    id: "CHECK_IN",
    name: "Check in",
    description: "Prepare travel check-in",
    category: "travel",
    priority: "high",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Trip title" }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_checkin", name: "Rimvio Check-in", platforms: WEB_MOBILE, priority: 100 }],
  }),
  CONFIRM_PLACE: cap({
    id: "CONFIRM_PLACE",
    name: "Confirm place",
    description: "Confirm meeting location",
    category: "mobility",
    priority: "high",
    executionMode: "deeplink",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "place", label: "Place", required: true }] },
    outputSchema: { kind: "url" },
    providers: [{ id: "naver_map", name: "Naver Map", platforms: WEB_MOBILE, priority: 100 }],
  }),
  CLARIFY_GOAL: cap({
    id: "CLARIFY_GOAL",
    name: "Clarify goal",
    description: "Structure a goal or project",
    category: "productivity",
    priority: "normal",
    executionMode: "prompt",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Goal title", required: true }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_prompt", name: "Rimvio Assistant", platforms: WEB_MOBILE, priority: 100 }],
  }),
  OPEN_EVENT: cap({
    id: "OPEN_EVENT",
    name: "Open event",
    description: "Review next event step",
    category: "productivity",
    priority: "normal",
    executionMode: "in_app",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [{ key: "title", label: "Event title" }] },
    outputSchema: { kind: "prompt" },
    providers: [{ id: "rimvio_calendar", name: "Rimvio Calendar", platforms: WEB_MOBILE, priority: 100 }],
  }),
  DISMISS_SURFACE: cap({
    id: "DISMISS_SURFACE",
    name: "Dismiss",
    description: "Defer this situation",
    category: "system",
    priority: "low",
    executionMode: "prompt",
    supportedPlatforms: WEB_MOBILE,
    inputSchema: { fields: [] },
    outputSchema: { kind: "none" },
    providers: [{ id: "rimvio_prompt", name: "Rimvio Assistant", platforms: WEB_MOBILE, priority: 100 }],
  }),
};
