/** 사용자-facing 카피 — L1 Story Layer. @see docs/RIMVIO_STORY_LAYER.md */

import { RIMVIO } from "@/lib/brand/rimvio";
import { STORY_L0, STORY_L1_NOUNS, STORY_L1_VERBS } from "@/lib/copy/story-layer";

export const copy = {
  brand: {
    name: RIMVIO.name,
    nameKo: RIMVIO.nameKo,
    lockup: RIMVIO.lockup,
    tagline: RIMVIO.northStarKo,
    northStar: RIMVIO.northStar,
  },
  product: {
    definition:
      "사용자의 경험 데이터를 시간·장소·사람·행동 단위로 구조화하고, 축적된 맥락을 기반으로 다음 행동을 제안·실행하는 Experience OS",
    definitionHuman:
      "하루 동안 남겨진 사진, 위치, 대화를 기억하고, 다음에 하고 싶을 일을 가장 편하게 이어주는 앱",
    oneLiner:
      "하루의 사진·위치·대화를 기억하고, 다음 일을 이어주는 앱",
    oneLinerSub:
      "경험이 쌓이면 맛집·길찾기·@실행이 맥락 안에서 열려요 · 자동 실행 없음",
    feedContext: "공유한 링크를 실행 카드로",
    peersContext:
      "대화에서 실행 버튼이 붙어요 · 프로필 길게 누르면 AI 렌즈",
    feedPeerTalkRoomHint: "대화에서 일정·장소를 잡아줘요",
    feedPeerTalkRoomLink: "ROOM 열기",
    feedPeerTalkStartedToast: "피드에서 대화 중 · 실행은 친구 ROOM에서",
    howToUseTitle: "Rimvio 쓰는 법",
    howToUseSub: "1분이면 @톡 · 실행 · 친구 버블이 정리돼요",
    howToUseCta: "사용 설명서 보기",
    lensCoachOn: "AI 렌즈 켜짐",
    lensCoachSub: "상대 말에 실행 버튼이 붙어요 · 탭할 때만 실행",
    storyEyebrow: "Rimvio 한 장 요약",
    story1Title: "친구 대화 → 실행 버튼",
    story1Body:
      "AI 렌즈가 상대 말에 일정·길찾기를 붙여요. 자동 실행 없음 · 탭할 때만.",
    story2Title: "친구 · 실행 — 같은 OS",
    story2Body:
      "친구 탭은 대화에서, 실행 탭은 링크·@명령에서. 다른 앱이 아니에요.",
    story3Title: "링크는 Shorts처럼",
    story3Body: "공유한 URL이 Action Dock 카드로 바뀝니다.",
  },
  nav: {
    feed: "피드",
    globe: "지구",
    people: "사람",
    capture: "기록",
    search: "검색",
    inbox: "인박스",
    room: "함께하기",
    peers: "친구",
    calendar: "캘린더",
    settings: "설정",
    start: "시작하기",
  },
  calendar: {
    pageHint: "림비오 맥락과 Google 동기화 일정이 구분되어 보여요",
    originRimvio: "앱에서 만든 맥락",
    originGoogle: "동기화 일정",
    originRimvioDetail: "림비오에서 만든 맥락 일정",
    originGoogleDetail: "Google Calendar에서 동기화된 일정",
    emptyTitle: "아직 등록된 일정이 없어요",
    emptyBody:
      "대화에서 일정을 말하거나, Google Calendar를 연결하면 prep surface에 쌓여요.",
    emptyHint:
      "일정을 말하거나 + 버튼으로 추가하면 여기에 쌓여요.",
    emptyListBody:
      "공유 타이머·예약 실행·일정 말하기가 여기에 쌓여요.",
    talkSchedule: "일정 말하기",
    connectGoogle: "Google Calendar 연결",
    connectSuccess: "Google Calendar 연결 완료",
    syncGoogle: "일정 동기화",
    syncing: "동기화 중…",
    syncShort: "GCal",
    syncSuccess: (count: number) => `${count}개 일정을 반영했어요.`,
    syncFail: "Google Calendar 동기화에 실패했습니다.",
    connectBannerTitle: "Google Calendar도 가져올까요?",
    connectBannerBody:
      "읽기 전용으로 연결하면 여행·미팅이 티켓·체크인 prep에 자동 반영돼요.",
    fullScreen: "전체 화면",
    integrations: "연동",
    sheetSummary: (rows: number, actions: number) =>
      `일정 ${rows} · 행동 ${actions}개 연결`,
    sheetSummaryEmpty: "저장된 일정·행동 제안",
    addSchedule: "일정 추가",
    addScheduleAria: "일정 추가",
    savedSchedule: "저장된 일정",
    allDay: "종일",
    googleConnectRequired: "Google Calendar 연결이 필요해요.",
    settingsIntegrations: "설정 → 서비스 연결",
    oauthSetupTitle: "Google OAuth 설정이 필요해요",
    oauthSetupBody:
      "Google Cloud Console에서 OAuth 클라이언트를 만들고 아래 Redirect URI를 등록한 뒤, .env.local에 키를 넣어 주세요.",
    oauthSetupRedirectLabel: "Redirect URI",
    oauthSetupScriptHint: "Windows: scripts/setup-google-calendar-oauth.ps1",
    oauthSetupPending: "서버 OAuth 미설정",
  },
  globe: {
    /** L0 — onboarding / marketing only */
    storyPersonal: STORY_L0.personal.ko,
    storyLaunch: STORY_L0.launchFilm.ko,
    title: "지구",
    subtitle: "당신이 지나간 순간이 여기 남아요",
    sharedTitle: "함께하는 지구",
    sharedSubtitle: "친구와 남긴 흔적을 이어서 볼 수 있어요",
    leaveTrace: STORY_L1_VERBS.leaveTrace,
    leaveHere: STORY_L1_VERBS.leaveHere,
    tapToPlace: "탭해서 여기에 남길 수 있어요",
    photoTrace: "사진으로 남기기",
    emptyTraces: "아직 흔적이 없어요. 한 줄만 남겨보세요.",
    emptyTracesSub: "사진·메모도 같은 자리에 이어져요",
    discoverNearby: "이 근처에서 남긴 흔적",
    stackPickerSub: (count: number) => `${count}개 · 하나를 골라보세요`,
    stackPickerShowAll: (overflow: number) => `외 ${overflow}개 · 전체 보기`,
    hubEmpty: "흔적이 쌓이면 여기에 나타나요",
    guide: {
      eyebrow: "시작하기",
      title: "그때 거기, 이렇게 남겨요",
      subtitle: "30초면 충분해요",
      step1Title: "지구를 돌려보세요",
      step1Body:
        "지나간 장소에 흔적이 핀으로 남아요. 사진이 쌓일수록 지도가 채워져요.",
      step2Title: "사진·동영상 남기기",
      step2Body:
        "화면 아래 ＋ 버튼 → 사진·동영상. 갤러리에서 고르면 그때·그곳에 붙어요.",
      step3Title: "확대·이동",
      step3Body:
        "한 손가락으로 돌리기 · 두 손가락 핀치로 가까이·멀리. 가운데를 기준으로 확대돼요.",
      step4Title: "순간과 맥락",
      step4Body:
        "핀을 탭하면 「순간 | 맥락」. 사진에서 왼쪽으로 밀면 글·친구·장소를 볼 수 있어요.",
      primaryCta: "첫 사진 남기기",
      secondaryCta: "알겠어요",
      detailLink: "자세한 설명 보기",
      settingsRow: "지구본 사용법",
      settingsRowSub: "30초 가이드 다시 보기",
    },
    recallArrivalNearby: "다시 왔어요 — 이 근처 흔적",
    recallArrivalSingle: (place: string) => `${place} — 그때 기억`,
    marketStubToast: "중고 흔적은 준비 중이에요. 지금은 경험으로 남겼어요.",
    inferredDomainEyebrow: "나중에 열릴 흔적",
    inferredDomainTitle: (label: string) => `${label} 흔적으로 읽혔어요`,
    inferredDomainBody:
      "지금은 내 경험으로만 저장돼요. 공개·거래는 다음 단계에서 열려요.",
    inferredDomainPriceHint: (price: string) => `가격 힌트 · ${price}`,
    recallArrival: "다시 왔어요 — 그때 기억",
    shareTraceLabelOff: "흔적 공개하기",
    shareTraceLabelOn: "공개 중 · 다시 누르면 나만 보기",
    shareTraceOn: "다른 사람도 이 흔적을 발견할 수 있어요",
    shareTraceOff: "나만 보는 흔적으로 바꿨어요",
    shareTraceFail: "공개 설정을 바꾸지 못했어요",
    pioneerHint: "이 근처에 남긴 첫 흔적이에요",
    externalTraceEyebrow: "다른 사람의 흔적",
    externalTraceReadOnly: "읽기만 · 다른 사람이 남긴 순간",
    externalDiscoveryEmpty: "아직 이 근처에 다른 흔적이 없어요",
    gatheringTraceEyebrow: "함께하는 흔적",
    gatheringTraceTitle: "모임 흔적을 남겼어요",
    gatheringTraceBody: "같이 갈 사람이 발견할 수 있어요 · 흔적 공개를 켜면 더 잘 보여요",
    gatheringTraceLineage: "이전 흔적에 이어서",
    gatheringHeadcountHint: (n: number) => `${n}명`,
    gatheringTimeHint: (hint: string) => `시간 · ${hint}`,
    gatheringComposeToast: "모임 흔적으로 남겼어요",
    bridgeInviteEyebrow: "함께하는 경험",
    bridgeInviteTitle: (host: string, title: string) =>
      `${host}님이 「${title}」에 초대했어요`,
    bridgeInviteBody:
      "수락하면 내 지도에도 같은 핀이 생겨요 · 상대 사진은 Rimvio 안에서만 볼 수 있어요",
    bridgeInviteHostFallback: "친구",
    bridgeInvitePlaceFallback: "여행",
    bridgeInviteOverflow: (n: number) => `외 ${n}건`,
    bridgeInviteAcceptCta: "함께 보기",
    bridgeInviteDeclineCta: "거절",
    bridgeInviteAccepted: "여행이 연결됐어요 · 내 지도에도 핀이 생겼어요",
    bridgeInviteDeclined: "초대를 거절했어요",
    bridgeInviteAcceptFail: "수락하지 못했어요",
    bridgeInviteDeclineFail: "거절하지 못했어요",
    contextWarmthLabel: "기억 온기",
    contextWarmthHint: "맥락이 많은 지역에 은은한 색 · 가까이 가면 사라져요",
    contextVideoSoundHint: "탭하면 소리",
    contextVideoSoundOff: "소리 켜기",
    contextVideoSoundOn: "소리 켜짐",
    bridgeInviteDismissAria: "나중에",
    bridgeInviteToast: (host: string, title: string) =>
      `${host}님이 「${title}」 경험을 공유했어요 · 수신함에서 확인`,
    bridgeInviteInboxTitle: "공유 받은 맥락",
    bridgeInviteInboxSubtitle: "수락하면 내 지도에도 같은 핀이 생겨요",
    bridgeInviteInboxEmpty: "받은 공유 요청이 없어요",
    bridgeInviteInboxChip: (n: number) => `공유 요청 ${n}건`,
    bridgeInviteInboxChipHint: "탭해서 수락 · 거절",
    inboxTitle: "수신함",
    inboxSubtitle: "공유 · 위치 확인 — 놓친 요청을 여기서 처리해요",
    inboxEmpty: "받은 알림이 없어요",
    inboxTriggerAria: "글로브 수신함",
    mediaPoolTitle: "사진·동영상 보관함",
    mediaPoolSubtitle: "GPS 없는 스크린샷 · 편집본 · 시간만 · 위치 대략 · 7일 보관",
    mediaPoolTriggerAria: "사진 보관함",
    mediaPoolEmptyTitle: "보관함이 비어 있어요",
    mediaPoolEmptyBody:
      "GPS 없는 사진·동영상은 여기에 쌓여요 · 골라서 맥락을 만들 수 있어요",
    mediaPoolAddButton: "추가",
    mediaPoolCreateButton: (n: number) =>
      n > 0 ? `선택 ${n}개로 맥락 만들기` : "맥락 만들기",
    mediaPoolSelectHint: "맥락에 넣을 사진·동영상을 골라주세요",
    mediaPoolAddingToast: "보관함에 넣는 중…",
    mediaPoolAddFailToast: "보관함에 넣지 못했어요",
    mediaPoolDeletedToast: "보관함에서 지웠어요",
    backerLinkLabel: "지원 · 투자",
    backerLinkAria: "Rimvio 지원·투자 문의 — 이메일로 연결",
    bulkClusterPeekToast: "사진 시간·위치 읽는 중…",
    bulkClusterGroupToast: "묶음 정리 중…",
    inboxSectionShare: "공유 받은 맥락",
    inboxSectionLocation: "위치 확인",
    inboxLocationTitle: (place: string, dwellLabel?: string) =>
      dwellLabel
        ? `${place} · ${dwellLabel} 쌓였어요`
        : `${place}에서 시간을 보낸 것 같아요`,
    globeLocationAccumulated: (dwellLabel: string) => `오늘 ${dwellLabel}`,
    inboxPhotoPlaceTitle: (place: string) => `${place}에서 찍은 사진 같아요`,
    inboxPhotoPlaceSuggestToast: (place: string) =>
      `${place}? 수신함에서 확인해 주세요`,
    inboxLocationConfirm: "맞아요",
    inboxLocationDismiss: "나중에",
    inboxLocationConfirmed: "위치를 확인했어요",
    inboxLocationConfirmFail: "확인하지 못했어요",
    inboxToastNew: (n: number) => `수신함에 새 알림 ${n}건`,
    bridgeShareSectionTitle: "친구에게 공유",
    bridgeShareSectionHint: "프로필을 누르면 초대가 바로 가요",
    bridgeShareSent: (name: string) => `${name}님에게 초대를 보냈어요`,
    bridgeShareFail: "초대를 보내지 못했어요",
    bridgeShareLoginRequired: "로그인하면 친구에게 공유할 수 있어요",
    bridgeShareNeedsFriendLogin:
      "친구도 Rimvio에 로그인해야 수신함에 초대가 보여요",
    inboxNeedsLogin: "로그인하면 공유 요청을 받을 수 있어요",
    inboxLoadFail: "수신함을 불러오지 못했어요 · 다시 시도해 주세요",
    bridgeGhostSheetBody:
      "수락하면 내 지구본에도 같은 핀이 생겨요 · 거절하면 사라져요",
    bridgeGhostAcceptCta: "내 지도에 남기기",
    bridgeMediaEyebrow: "함께 보는 순간",
    bridgeParticipantsLine: (names: readonly string[]) => {
      const list = names.filter(Boolean);
      if (list.length === 0) {
        return "함께하는 경험";
      }
      if (list.length === 1) {
        return `${list[0]}와 함께`;
      }
      if (list.length === 2) {
        return `${list[0]} · ${list[1]}`;
      }
      return `${list[0]} 외 ${list.length - 1}명`;
    },
    bridgeMediaSwipeHint: (n: number) =>
      n > 1 ? `${n}개의 순간 · 아래 필름스트립 또는 스와이프` : "스와이프로 넘기기",
    bridgeMediaPending: (name: string, kind: "photo" | "video") =>
      `${name}님 ${kind === "video" ? "동영상" : "사진"} 도착 중`,
    bridgeMediaAuthorChip: (name: string) => `${name}님의 순간`,
    bridgeContextSwipeHint: "맥락 보기",
    bridgeMediaSwipeBackHint: "순간으로",
    bridgeContextPageEyebrow: "맥락",
    bridgeMediaContextTabMoments: "순간",
    bridgeMediaContextTabContext: "맥락",
    bridgeContextRecallEyebrow: "그때 거기",
    bridgeContextEnvironmentEyebrow: "환경",
    bridgeContextPeopleEyebrow: "함께한 사람",
    bridgeContextActionsEyebrow: "이어가기",
    bridgeContextTalkCta: "톡 열기",
    bridgeContextTalkHint: "함께한 대화로 이어요",
    bridgeContextFilterAll: "전체",
    bridgeContextFilterMoments: (name: string) => `${name} 순간`,
    bridgeContextNavCta: "길찾기",
    bridgeContextScheduleCta: "일정",
    bridgeContextNoteCta: "회고",
    bridgeContextNoteEmpty: "한 줄 회고 남기기",
    bridgeContextNoteSaved: "회고를 남겼어요",
    bridgeContextPoolCta: "빠진 순간",
    bridgeContextPoolHint: (n: number) =>
      n > 0 ? `맞는 사진 ${n}장` : "보관함 확인",
    bridgeContextWeatherLoading: "날씨 확인 중…",
    bridgeContextTrafficLoading: "교통 확인 중…",
    bridgeContextEnvironmentEmpty: "장소를 확인하면 날씨·길 정보를 보여드려요",
    pinContextDetailsExpand: "맥락 펼치기",
    pinContextDetailsCollapse: "맥락 접기",
    pinContextDetailsFallback: "대표 장면 · 공유 · 흔적",
    ingestPlaceholder: "@길찾기 역이름 · 사진 · 링크 · 메모 — 여기에 남기기",
    ingestAttachPlaceholder: (title: string) => `「${title}」에 @ · 사진 · 메모`,
    ingestAttachHint: (title: string) => `「${title}」에 이어서 남기기`,
    ingestSuccess: "흔적을 남겼어요",
    ingestFail: "남기지 못했어요",
    createTitle: STORY_L1_VERBS.create,
    createPlaceStep: "장소 확인",
    createPlacePlaceholder: "예: 상하이 · 홍콩 · 도쿄 · 신림동",
    createPlaceHint:
      "해외는 도시·나라 이름을 넣으면 위치를 확인해요 · 국내는 동·역 이름도 돼요",
    createPlaceOverseasEyebrow: "해외 지역",
    createPlaceOverseasBody:
      "구글맵 후보에서 맞는 도시·지점을 골라 주세요 · 자동으로 한국에 박지 않아요",
    createPlaceOverseasLoading: "구글에서 해외 장소 찾는 중…",
    createPlaceOverseasNoResults:
      "후보가 없어요 · 영문 도시명을 써 보거나 구글맵에서 확인해 주세요",
    createPlaceApproximateCta: (label: string) => `${label} 중심에 대략 박기`,
    departureHubStep: "출발 허브",
    departureHubEyebrow: "비행기",
    departureHubTitle: (place: string) => `「${place}」에 출발 허브를 연결할까요?`,
    departureHubBody:
      "집과는 다른 곳, 공항 쪽에 출발 핀을 박아요 · 탭하면 그 여행 항공으로 이어져요",
    departureHubRecommended: "추천",
    departureHubSkip: "나중에 할게요",
    departureHubConnected: (airport: string) => `${airport} 출발 허브를 연결했어요`,
    departureHubConnectFail: "출발 허브를 연결하지 못했어요",
    contextHubEyebrow: "자원",
    contextHubSectionTitle: "맥락에 맞는 허브",
    contextHubSectionBody:
      "필요할 때 꽂고, 필요 없으면 뺄 수 있어요 · 탭하면 항공·이동으로 이어져요",
    contextHubAdd: "허브 추가",
    contextHubRemove: (label: string) => `${label} 허브 빼기`,
    contextHubDisconnected: (label: string) => `${label} 허브를 뺐어요`,
    contextHubDisconnectFail: "허브를 빼지 못했어요",
    contextHubEmpty: "아직 연결한 허브가 없어요 · + 로 공항·자원을 꽂아 보세요",
    contextHubDepartureKind: "출발 공항",
    contextHubDraftTitle: "미리 꽂아 둘 허브",
    contextHubDraftBody: "맥락을 박을 때 함께 연결돼요 · 나중에 핀에서도 바꿀 수 있어요",
    contextHubOpenFlight: "항공권 보기",
    dockExpandAria: "필터·위치 펼치기",
    dockCollapseAria: "필터·위치 접기",
    createFail: "맥락을 만들지 못했어요",
    listTitle: "내 맥락",
    manageTitle: "관리",
    manageDeleteConfirm: (count: number) =>
      count === 1
        ? "선택한 맥락을 지울까요?\n지구에서 사라지며, 사진·기록은 기기에 남아요."
        : `선택한 맥락 ${count}개를 지울까요?\n지구에서 사라지며, 사진·기록은 기기에 남아요.`,
    manageDeleteSuccess: (count: number) =>
      count === 1 ? "맥락 1개를 지웠어요" : `맥락 ${count}개를 지웠어요`,
    manageDeleteFail: "맥락을 지우지 못했어요",
    manageSelectHint: "맥락을 선택하세요",
    listEmptyFuture: "다가올 맥락이 없어요",
    listEmptyNow: "지금 겹치는 맥락이 없어요",
    listEmptyPast: "지난 맥락이 없어요",
    listEmptyAll: "아직 맥락이 없어요.\n흔적 남기기로 첫 순간을 남겨 보세요.",
    listManualBadge: " · 직접 만든 맥락",
    notFound: "맥락을 찾지 못했어요",
    contextLabel: STORY_L1_NOUNS.context,
    /** Settings only — power user */
    settingsLocation: "위치",
    settingsGps: "GPS 추적",
    settingsDwellHint: "같은 장소에 머물면 맥락이 쌓여요",
    /** @deprecated use leaveTrace / emptyTraces */
    placePin: STORY_L1_VERBS.leaveHere,
    photoPin: "사진으로 남기기",
    emptyPins: "아직 흔적이 없어요. 한 줄만 남겨보세요.",
  },
  search: {
    title: "수집",
    subtitle: "사진·링크·메모 → 오늘 경험에 자동으로 붙기",
    emptyHint: "여행·만남 일정을 잡아두면 더 정확해요",
    emptySubhint: "사진·링크·메모를 올리면 Feed 경험 노드에 모여요",
    placeholder: "사진·링크·메모 · 민수 제주처럼 관련 경험 찾기",
    ingressHint: "사진·링크·메모 올리기 · 민수·제주로 관련 경험 검색",
    ingressEyebrow: "수집",
    ingressTitle: "오늘 경험에 담기",
    ingressPhoto: "사진·영상 — 촬영 또는 앨범",
    ingressLink: "링크 붙여넣기",
    ingressMemo: "짧은 메모·일정 메모",
    aiDeferredHint: "맛집·길찾기는 피드에서 경험을 고른 뒤 @로 실행해요",
    feedLink: "피드에서 경험 보기",
    blockedGenericQuery: "여기는 담는 곳이에요",
    blockedGenericQuerySub: "피드에서 경험을 고른 뒤 맛집·길찾기를 물어보세요",
    run: {
      eyebrow: "경험 맥락 실행",
      fallbackTitle: "선택한 경험",
      contextLine: (feature: string) => `@${feature} — 피드에서 이어서 실행`,
      backToFeed: "피드로 돌아가기",
      placeholder: "@명령 입력 · 이 경험 맥락",
    },
    contextSearch: {
      eyebrow: "관련 맥락",
      titleForQuery: (query: string) => `「${query}」 관련 경험`,
      empty: "아직 맞는 경험이 없어요. 사진·메모를 올리면 다음부터 찾을 수 있어요.",
      openOnFeed: "피드에서 이어 보기",
      clear: "검색 닫기",
      peoplePrefix: "사람",
      experiencePrefix: "경험",
      peopleButton: (n: number) => `사람 ${n}`,
      experienceButton: (n: number) => `경험 ${n}`,
      ingressHint: "민수(사람) · 제주(경험)… 축별로 쌓인 경험을 검색해요",
      timingHint:
        "여행·만남·@ 실행을 앞두고 관련 추억을 찾을 때 쓰세요 · 대화 중엔 조용히 쌓아요",
    },
  },
  peers: {
    title: "친구",
    subtitle:
      "대화에서 실행 버튼이 붙어요 · 프로필 길게 누르면 AI 렌즈",
    hubHint: "대화 목록에서 친구를 탭 · 친한 5는 아래에서 고정",
    emptyFeedLink: "링크만 쓰려면 실행 탭",
    emptyTitle: "친한 친구를 연결해 보세요",
    emptyBody:
      "친구를 추가하면 대화와 실행 버튼을 함께 쓸 수 있어요.",
    emptyAddCta: "친구 추가",
    demoTitle: "예시 대화 (읽기 전용)",
    demoHint: "친구를 추가하면 실제 DM·AI 렌즈를 쓸 수 있어요",
    demoLensTap: "친구 추가 후 탭해서 실행하세요",
    guestSignInHint:
      "Google로 시작하면 친구 버블·AI 렌즈를 쓸 수 있어요",
    friendAdd: {
      sheetTitle: "친구 추가",
      sheetSubtitle: "Google로 가입한 친구는 Gmail만 입력해도 돼요",
      pinTitle: (slot: number) => `${slot}번 버블에 고정`,
      pinSubtitle: "친구를 찾아 이 자리에 고정해요",
      modeEmail: "이메일",
      modeId: "@아이디",
      modePhone: "번호",
      placeholderEmail: "친구 Gmail",
      placeholderId: "rimvio 아이디",
      placeholderPhone: "01012345678",
      copyInvite: "친구에게 보낼 문구 복사",
      copyInviteDone: "복사했어요 · 카톡에 붙여넣기",
      inviteWithId: (id: string, url: string) =>
        `Rimvio에서 친구 추가해요\n@${id}\n${url}`,
      inviteNoId: (url: string) => `Rimvio에서 친구 추가해요\n${url}`,
      myIdLabel: "내 @아이디",
      previewTap: "탭해서 친구 추가",
      previewConfirm: "친구 추가",
      previewPin: "여기에 고정",
      previewAdding: "추가 중…",
      loginRequired: "Google 로그인 후 친구를 추가할 수 있어요",
      loginCta: "로그인하기",
      listCta: "친구 추가",
      listEmptyHint: "이메일 · @아이디 · 번호로 찾을 수 있어요",
    },
    friendRail: {
      title: "대화",
      subtitle: (n: number) => `친구 ${n}명`,
      unread: (n: number) => (n > 99 ? "새 톡 99+" : `새 톡 ${n}`),
      empty: "아직 친구가 없어요",
      emptyHint: "이메일 · @아이디 · 번호로 추가",
      pinnedBadge: "친한 5",
      startChat: "대화 시작",
      newMessages: (n: number) => `새 메시지 ${n > 99 ? "99+" : n}`,
      pinnedSection: "친한 5",
      pinnedSectionHint: "항상 보이는 관계 · AI 렌즈",
      groupsSection: "단톡",
      createGroup: "+ 만들기",
      createGroupFirst: "첫 단톡 만들기",
    },
  },
  feed: {
    title: "피드",
    subtitle: "오늘 쌓인 경험",
    askAi: "AI에게 더 물어보기",
    experience: {
      heroEyebrow: "오늘",
      heroTitle: "쌓인 경험",
      heroSubtitle: "사진·체류·사람이 자동으로 모여요",
      autoAttachedHint: "자동으로 붙었어요",
      verifyDeferHint: "맞아요 후에 길찾기·맛집이 열려요",
      pendingVerify: (n: number) => `확인할 경험 ${n}개`,
      recallChip: "그때 거기",
      recall: {
        expand: "그때 거기 펼치기",
        collapse: "접기",
        empty: "아래에서 오늘 경험을 선택하세요",
        miniHint: "탭해서 공간·시간 기억 보기",
        shorts: {
          playToggle: "영상 재생 · 일시정지",
          loading: "그때 미디어 불러오는 중…",
          memoryPlaceholder: "남긴 사진·영상이 여기 재생돼요",
        },
      },
      run: {
        at: "@실행",
        sectionLabel: "이 경험에서 실행",
        hint: "맥락이 잡힌 뒤 @로 길찾기·맛집을 실행해요",
      },
      relatedContext: {
        prefix: "관련 · ",
        peoplePrefix: "사람",
        experiencePrefix: "경험",
        peopleButton: (n: number) => `사람 ${n}`,
        experienceButton: (n: number) => `경험 ${n}`,
        buttonLabel: (n: number) => (n > 0 ? `관련 ${n}` : "관련"),
        buttonAria: (n: number) => `관련 맥락 ${n}개 보기`,
      },
      emptyCta: "사진 올리기",
    },
    today: {
      ariaLabel: "오늘의 경험",
      eyebrow: "오늘",
      title: "쌓인 경험",
      subtitle: "사진·체류·사람이 자동으로 모여요",
      count: (n: number) => `${n}개`,
      viewAll: "전체 보기",
      hint: "탭해서 그때 거기 보기",
      quickActions: "필터",
      filterAll: "전체",
      filterEmpty: "해당 경험이 없어요",
      filterEmptyHint: "다른 칩을 누르거나 전체를 선택해 보세요",
      taxonomy: {
        searchPlaceholder: "제주 · 여행 · 민수…",
        searchAria: "쌓인 경험 검색",
        clearSearch: "검색 지우기",
        l1: "대분류",
        l2: "중분류",
        l3: "소분류",
        reset: "필터 초기화",
        emptyHint: "검색어나 분류를 바꿔 보세요",
      },
      sectionToday: "오늘의 경험",
      sectionTomorrow: "내일",
      sectionLater: "이후",
      sectionUnset: "예정",
      empty: "아직 오늘 경험이 없어요",
      emptyHint: "검색에 사진·링크를 올리면 여기 쌓여요",
      together: "함께",
      peerDetail: {
        title: "약속 상대",
        rimvioId: "Rimvio ID",
        email: "이메일",
        openChat: "대화 열기",
        close: "닫기",
      },
    },
    queue: {
      ariaLabel: "다가오는 경험",
      eyebrow: "더 보기",
      title: "다가오는 경험",
      filterAll: "전체",
      empty: "다른 일정은 비어 있어요",
      expandAria: "큐 펼치기",
      collapseAria: "큐 접기",
      collapsedEmpty: "비어 있어요",
      collapsedCount: (count: number) => `${count}개 대기`,
      collapsedWithPeek: (count: number, title: string) => `${count}개 · ${title}`,
      nowFocus: (title: string) => `지금 · ${title}`,
      searchLink: "피드에서 경험 고른 뒤 @실행",
      sectionInProgress: "진행 중",
      sectionContextActions: "경험 안 실행",
      sectionUpNext: "다음",
    },
    newLinkSaved: "저장되었습니다",
    undoDelete: "삭제되었습니다",
    undo: "되돌리기",
    emptyPaste: "링크 붙여넣기",
    emptyShareHint: "다른 앱에서 공유해도 바로 실행 버튼으로 바뀌어요",
    swipeToRoom: "왼쪽으로 밀면 함께하기에 추가",
    linkAddPill: "링크 추가",
    capturePill: "담기",
    remotePill: "리모컨",
    captureSheetTitle: "링크 · 사진 담기",
    captureSheetHint: "URL·스크린샷을 보내면 Action Dock으로 바꿔 드려요",
    capturePaymentCamera: "📷 계좌 촬영 → 송금",
    capturePaymentFound: "계좌번호를 찾았어요 — 송금 리모컨이 준비됐어요",
    captureIntentFound: "사진 분석 중 — 카드에 가게 정보가 뜰 거예요",
    captureCamera: "📷 사진 찍기",
    captureCameraHint: "메뉴·상품·영수증·명함·티켓·WiFi 등 자동 인식",
    captureOr: "또는",
    screenshotPick: "앨범에서 스크린샷 선택",
    screenshotProcessing: "글자 읽는 중…",
    screenshotFailed: "사진에서 내용을 읽지 못했어요",
    screenshotNoIntent: "가게 이름이나 상품명을 찾지 못했어요 · 더 선명한 캡처를 써 보세요",
    screenshotInvalid: "이미지 파일만 선택할 수 있어요",
    screenshotConfirmPrompt: (query: string) => `「${query}」 맞아요?`,
    screenshotConfirmYes: "맞아요",
    screenshotConfirmRetry: "다시 고르기",
    linkAddLow: "입력 2~3개만 더 쌓으면 Action 추천이 맞춰져요",
    linkAddSingle: "첫 Action이에요 · 더 쌓을수록 Dock이 똑똑해져요",
    linkAddEnd: "끝까지 봤어요 · 말을 걸거나 링크를 추가해 보세요",
    linkAddRecentEmpty: "최근 7일 입력이 없어요 · 말을 걸거나 공유해 보세요",
    linkAddPaste: "링크 붙여넣기 →",
  },
  inbox: {
    title: "인박스",
    subtitle: "공유·붙여넣기한 것 → 실행으로 바꿔 드릴게요",
    paste: "링크 붙여넣기",
    pastePlaceholder: "링크를 붙여넣어 주세요",
    pasteSubhint: "여러 개는 줄마다",
    select: "선택",
    cancelSelect: "취소",
    selectAll: "전체 선택",
    selectedCount: (n: number) => `${n}개 선택됨`,
    sendBulk: (n: number) => `${n}개 보내기`,
    sendFiltered: (n: number) => `목록 ${n}개 한 번에 보내기`,
    sendToRoom: "함께하기에 추가",
    bulkCopied: "공유 문구를 복사했습니다",
    bulkShared: (n: number) => `${n}개를 보냈습니다`,
    bulkRoomAdded: (n: number, room: string) =>
      `${room}에 링크 ${n}개를 추가했습니다`,
    multiSaved: (n: number) => `링크 ${n}개를 저장했습니다`,
    invalidFormat: "링크 형식을 확인해 주세요",
    alreadyExists: "이미 저장된 링크입니다",
    clipboardUnsupported: "이 브라우저에서는 붙여넣기를 지원하지 않습니다",
    clipboardEmpty: "클립보드가 비어 있습니다",
    clipboardPermission: "붙여넣기 권한이 필요합니다",
    emptyTitle: "아직 받은 입력이 없습니다",
    emptyHint: `위에 붙여넣거나, 다른 앱에서 ${RIMVIO.name}으로 공유해 주세요`,
    emptyCategory: "이 카테고리에 링크가 없습니다",
    hintInteraction:
      "탭하면 바로 열기 · 길게 누르면 여러 개 선택 · 선택 후 원하는 곳으로 옮겨 드립니다",
    selectPrompt: "옮길 링크를 선택해 주세요",
    openSelected: "열기",
    moveToFeed: "피드",
    savedLabel: "저장됨",
    openLinksCount: (n: number) => `인박스 ${n}개`,
    clearedToday: (n: number) => ` · 오늘 ${n}개 마무리`,
    archiveLink: (n: number) => `보관함 ${n}개`,
  },
  burner: {
    work: "일",
    health: "건강",
    friends: "관계",
    growth: "성장",
  },
  coaching: {
    openMany: (n: number) =>
      `인박스 ${n}개 — 하나만 실행해도 훨씬 가벼워집니다`,
    workEvening: (pct: number, growthLabel: string) =>
      `오늘 일 ${pct}% — ${growthLabel} 링크는 내일 아침으로 미뤄도 괜찮아요`,
    workDay: (pct: number) =>
      `일 ${pct}% — 가장 가벼운 것부터 차근차근 시작해 보세요`,
    growthEvening: (growthLabel: string) =>
      `저녁 ${growthLabel} 시간 — AI 요약으로 가볍게 마무리해 보세요`,
    balanced: (a: string, b: string, need: string) =>
      `${a}·${b}가 비슷해요 — ${need}에 맞는 것부터 시작해 주세요`,
    dominant: (burner: string, pct: number, psyche: string) =>
      `${burner} ${pct}% · ${psyche}`,
  },
  room: {
    hubTitle: "함께하기",
    hubSubtitle: "함께 볼 링크 · 1인 1방",
    pageSubtitle: "함께 볼 링크",
    live: "지금 함께 보는 중",
    connecting: "연결 중…",
    emptyTitle: "아직 링크가 없습니다",
    emptyHint: "피드에서 ← 밀거나 공유 → 함께하기에 추가해 보세요",
    roomLimitHint: "방은 1개만 · 피드에서 ← 밀어 추가",
    statusOpen: "아직 남아 있어요",
    statusDone: "완료",
    doneButton: "완료",
    doneToast: "완료되었습니다",
    doneToastHint: "함께하는 분들에게도 표시됩니다",
    crownLabel: (name: string, isSelf: boolean) =>
      isSelf ? "오늘의 MVP는 바로 나" : `${name}님이 MVP`,
    inviteTitle: "함께하기 초대",
    pickerTitle: "어느 방에 추가할까요?",
    pickerHint: "탭하면 바로 들어갑니다",
    createAndAdd: "새 방 만들고 추가",
    linkRoomLive: "함께하기 · 실시간",
    countOpen: (n: number, done: number) =>
      `${n}개 남음 · ${done}개 완료`,
    dockDone: "완료",
    dockComment: "댓글",
    dockSimilar: "비슷한",
    dockSpark: "상상",
    addedToRoomHint: (room: string) => `${room}에 추가됨 · 피드는 이어서 볼 수 있어요`,
    addedToRoom: "함께하기에 추가되었습니다",
    createFail: "방을 만들지 못했습니다. 잠시 후 다시 시도해 주세요",
    openRoom: "방 열기",
    roomNamePlaceholder: "방 이름 (예: 주말 여행)",
    roomNamePlaceholderShort: "예: 제주 여행, 팀 프로젝트",
    friendRoomsTitle: "친구 방",
    friendSendTitle: "어느 방으로 보낼까요?",
    friendSendHint: "추가된 친구 방을 고르거나, 방 주소를 붙여넣어 주세요",
    friendRoomLabel: "친구 방",
    friendRoomsEmpty: "아직 친구 방이 없어요. 아래에 초대 주소를 붙여넣어 주세요",
    friendRoomUrlPlaceholder: "예: https://rimvio.app/r/주말여행-ab12",
    friendRoomUrlSend: "주소로 보내기",
    friendRoomAdded: "친구 방이 추가되었습니다",
    friendRoomSent: (room: string) => `「${room}」에 보냈습니다`,
    friendRoomSentHint: "잠시 후 상대방 방에서 확인할 수 있습니다",
    friendRoomInvalidUrl: "방 주소 형식을 확인해 주세요",
    friendRoomSame: "지금 보고 있는 방이에요",
    friendRoomSendFail: "링크를 보내지 못했습니다. 잠시 후 다시 시도해 주세요",
    dockSendFriend: "친구 방",
    phaseMap: "방이 지금 길찾기 모드예요",
    phaseCommerce: "방이 지금 쇼핑·가격 비교 모드예요",
    phaseTravel: "방이 지금 여행·예약 모드예요",
    phaseMedia: "방이 지금 영상·재생 모드예요",
    phaseSocial: "방이 지금 공유·문의 모드예요",
    phaseResearch: "방이 지금 검색·요약 모드예요",
  },
  beam: {
    brand: RIMVIO.lockup,
    loading: "불러오는 중…",
    notFound: "링크를 찾을 수 없습니다",
    hint: "주소를 찾을 필요 없어요. 아래 버튼만 눌러 주세요",
    copied: "복사되었습니다",
    saveToPocket: "인박스에 저장",
    savedToPocket: "인박스에 저장되었습니다",
    alreadyInPocket: "이미 저장되어 있습니다",
    pocketHint: "나중에 보려면 한 번만 눌러 주세요",
    openInbox: "인박스에서 보기",
  },
  share: {
    beamCopied: "공유 문구를 복사했습니다",
    sent: (label: string) => `${label}(으)로 보냈습니다`,
    pasteHint: "붙여넣기만 하면 바로 열 수 있습니다",
    pasteOnly: "붙여넣기만 하면 됩니다",
    retry: "잠시 후 다시 시도해 주세요",
    honeycombHint: "탭하면 복사되고 앱이 열립니다",
    otherWays: "다른 방법",
    roomInFeed: "함께하기에 추가",
    roomCollab: "함께하기",
    beamShare: "다른 앱으로 보내기",
    directShare: "친구에게 보내기",
    footnote:
      "혼자 실행할 입력은 실행 화면, 함께 볼 것은 함께하기 — 편하게 나눠 두었습니다",
  },
  auth: {
    loginTagline: "말하고, 공유하고 — 실행은 탭 한 번",
    loginPrompt: "Google로 시작한 뒤, 친구·링크에서 실행만 골라요.",
    googleLogin: "Google로 시작하기",
    googleContinue: "Google로 계속하기",
    loggedInAs: (name: string) =>
      `${name}님, 반갑습니다. 실행 기록이 이 계정과 함께합니다`,
    loginHint:
      "기기를 바꿔도 링크를 이어 받고 싶을 때 로그인해 주세요. 로그인 없이도 편하게 쓰실 수 있습니다",
    checking: "로그인 상태를 확인하는 중…",
    logout: "로그아웃",
    logoutOk: "다음에 또 만나요",
    loginFail: "로그인에 실패했습니다",
    loginFailHint: "잠시 후 다시 시도해 주세요",
    invalidSupabaseKeyHint:
      "Vercel의 NEXT_PUBLIC_SUPABASE_ANON_KEY가 잘못됐어요. Supabase → Settings → API → anon public 키를 다시 붙여넣고 Redeploy 하세요.",
    loginIncomplete: "로그인이 중단되었습니다",
    devSetupTitle: "로그인 준비 중",
    devSetupHint: "서버 연결이 완료되면 Google로 바로 시작하실 수 있습니다",
    setupTitle: "Google 로그인 연결",
    setupBody: "Supabase + Google OAuth 키를 넣으면 아래 버튼이 켜집니다.",
    setupStep1: "Supabase → Authentication → Providers → Google 활성화",
    setupStep2: "Google Cloud redirect URI: Supabase …/auth/v1/callback (아래 참고)",
    setupStep3: ".env.local에 SUPABASE URL · ANON KEY 추가 후 npm run dev 재시작",
    setupDocLink: "설정 가이드 보기",
    setupEnvHint: "터미널: npm run auth:check",
    loginStrip: "Google로 로그인하면 링크가 계정에 저장됩니다",
    requiredTitle: "로그인이 필요합니다",
    requiredBody: "Rimvio의 모든 기능은 Google 계정으로 로그인한 뒤 이용할 수 있습니다.",
    requiredRedirect: "로그인 화면으로 이동 중…",
    logoutFail: "로그아웃에 실패했습니다. 잠시 후 다시 시도해 주세요",
    guestName: "손님",
    signedInTitle: "로그인되었습니다",
  },
  profileSetup: {
    loginSub: "Google 한 번이면 끝 · 이어서 Rimvio ID만 정하면 친구가 나를 찾을 수 있어요",
    googleCardTitle: "Google로 3초 만에 시작",
    googleCardBody:
      "로그인 후 이름·Rimvio ID만 정하면 친구·실행 탭을 바로 쓸 수 있어요",
    googleCardFoot: "Human decides · 실행은 항상 내가 탭할 때만",
    loading: "프로필 불러오는 중…",
    introTitle: "Rimvio는 Experience OS예요",
    introBody:
      "하루의 사진·위치·대화를 기억하고, 쌓인 맥락으로 다음 일을 이어줘요.",
    introTapHint: "자동 실행 없음 · 탭할 때만 실행",
    introCta: "프로필 만들기",
    welcomeTitle: "Google 연결 완료",
    welcomeBody:
      "이제 Rimvio에서 쓸 이름과 @아이디만 정하면 돼요. 친구는 ID·이메일·번호로 찾을 수 있어요",
    welcomeCta: "프로필 만들기",
    nameTitle: "1/3 · 표시 이름",
    nameHint: "ROOM·피드에 보이는 이름이에요",
    nameRequired: "이름을 입력해 주세요",
    idTitle: "2/3 · Rimvio ID",
    idHint: "카톡 ID처럼 친구가 @아이디로 검색해요 · 한 번 정하면 검색용으로 씁니다",
    useSuggestedId: (id: string) => `추천 ID 사용 · @${id}`,
    phoneTitle: "3/3 · 휴대폰 (선택)",
    phoneHint: "번호로도 친구를 찾을 수 있어요 · 나중에 설정에서 바꿀 수 있어요",
    skipPhone: "나중에 할게요",
    next: "다음",
    back: "이전",
    finish: "시작하기",
    saving: "저장 중…",
    saveFailed: "저장에 실패했어요",
    completeToast: "기본 프로필이 준비됐어요",
    doneTitle: "준비 완료",
    doneBody: "이제 관계 버블에서 친구를 고정하고 대화를 시작해 보세요",
    doneCta: "ROOM으로",
  },
  sync: {
    title: "실행 화면으로 옮기기",
    hint: `다른 기기의 ${RIMVIO.name}에서도 그대로 이어 받으실 수 있습니다`,
    export: "내보내기",
    import: "가져오기",
    exportShared: "파일로 공유했습니다",
    exportCopied: "복사되었습니다 — 다른 기기에 붙여넣어 주세요",
    exportDownload: "파일을 받았습니다",
    importOk: (n: number) => `링크 ${n}개를 다시 모았습니다`,
    importFail: "가져오기에 실패했습니다",
    importFailHint: `${RIMVIO.name}에서 만든 백업 파일인지 확인해 주세요`,
  },
  settings: {
    profileNameSectionTitle: "표시 이름",
    profileNameSectionHint: "함께하기·피드에서 보이는 이름이에요",
    profileNameLabel: "이름",
    profileNamePlaceholder: "예: 링크 모으는 민지",
    profileAvatarLabel: "내 림비오",
    profileAvatarFixed: "색은 바꿀 수 없어요 · 처음 배정 그대로",
    profileRarePurple: "✨ 희귀 보라 림비오 · 100명 중 1명",
    profileRareGranted: "보라 림비오 당첨! ✨ 운명 수정 완료",
    profileSaved: "프로필을 저장했습니다",
    accountProfile: {
      sectionTitle: "Rimvio 계정",
      sectionHint: "프로필 사진·이름·ID·번호 — 카톡처럼 친구가 나를 찾아요",
      photoTapHint: "사진을 눌러 등록",
      photoRemove: "사진 삭제",
      photoChanged: "프로필 사진을 바꿨어요",
      photoRemoved: "프로필 사진을 삭제했어요",
      displayNameLabel: "표시 이름",
      displayNamePlaceholder: "예: 지훈",
      rimvioIdLabel: "Rimvio ID",
      rimvioIdPlaceholder: "rimvio_jihun",
      rimvioIdHint: "4~20자 · 영문 소문자로 시작 · 친구 검색용",
      phoneLabel: "휴대폰 번호",
      phonePlaceholder: "010-1234-5678",
      phoneHint: "비우면 번호로는 검색되지 않아요",
      emailLabel: "로그인 이메일",
      emailHint: "Google 계정과 연결된 주소 (변경 불가)",
      save: "프로필 저장",
      saving: "저장 중…",
      saved: "프로필을 저장했습니다",
      saveFailed: "저장에 실패했어요",
      loading: "프로필 불러오는 중…",
      editTitle: "프로필 수정",
      edit: "수정",
      cancel: "취소",
      noDisplayName: "이름 없음",
      noRimvioId: "Rimvio ID를 만들어 주세요",
      idCopied: "ID를 복사했어요",
      copyFailed: "복사에 실패했어요",
      moreInSettings: "설정에서 더 보기",
      noChanges: "변경된 내용이 없어요",
    },
    oddsTitle: "림비오 색 뽑기 확률",
    oddsHint: "처음 들어올 때 딱 한 번 · 색은 평생 고정",
    oddsBadge: "1회 한정",
    oddsMine: "내꺼",
    oddsUltraRare: "100명 중 1명",
    oddsFooter: "보라는 브랜드 원본 👑 · 다시 뽑기는 없어요 (진짜로)",
    oddsScrollHint: "↓ 손가락으로 내려 전체 확률 보기",
    drawEyebrow: "1회 한정",
    drawTitle: "나만의 림비오 색 뽑기",
    drawHint: "딱 한 번만! 뽑힌 색은 평생 고정 · 홈 아이콘과 프로필에 바로 반영돼요",
    drawButton: "두근두근! 색 뽑기 🎲",
    drawButtonRolling: "뽑는 중… 두근두근",
    drawRolling: "두근두근… 어떤 색일까?",
    drawIdleCaption: "버튼을 누르면 색이 정해져요",
    drawDoneLabel: "내 림비오 확정!",
    drawDoneHint: "홈 아이콘과 프로필에 이 색이 적용됐어요",
    drawReveal: (color: string, emoji: string) => `${emoji} ${color} 림비오 당첨!`,
    drawRevealPurple: "👑 보라 림비오! 100명 중 1명 · 운명의 색",
    drawResetOk: "처음부터 다시! 이제 색을 뽑아보세요 🎲",
    drawFeedBannerTitle: "아직 림비오 색을 안 뽑았어요",
    drawFeedBannerHint: "한 번만 뽑으면 홈 아이콘과 프로필에 반영돼요",
    drawFeedBannerCta: "뽑기",
    drawPurpleRevealEyebrow: "울트라레어",
    drawPurpleRevealTitle: "보라 림비오!",
    drawPurpleRevealBody: "브랜드 원본 색 · 평생 고정 · 진짜 운명이에요",
    drawPurpleRevealOdds: "👑 100명 중 1명만 받는 색",
    drawPurpleRevealDismiss: "멋져요! ✨",
    drawPendingProfile: "아직 색을 뽑지 않았어요 · 위에서 먼저 뽑기!",
    oddsPending: "색을 뽑으면 내 확률표에 ✓ 표시가 생겨요",
    tasteTitle: "추천 취향",
    tasteHint: (max: number) =>
      `링크에 맞는 행동 버튼을 고를 때 참고해요 · 최대 ${max}개`,
    tasteSaved: "추천 취향을 반영했습니다",
    tasteAuto: "자동 추천으로 돌아갔습니다",
    tasteAutoHint: "선택 없음 — 저장한 링크 패턴으로 자동 추천",
    tasteActive: (labels: string) => `우선: ${labels}`,
    scheduleTitle: "실행 예약 매체",
    scheduleHint: "기본값 · 예약할 때마다 카드마다 바꿀 수 있어요",
    scheduleBadge: "기본값",
    scheduleSaved: "실행 예약 매체를 저장했습니다",
    schedulePwaHint: "홈 화면에 추가하면 알림이 더 잘 와요",
    scheduleActive: (label: string) => `지금 기본: ${label}`,
    scheduleSheetTitle: "어디에 저장할까요?",
    scheduleSheetHint: (actionLabel: string) =>
      `${actionLabel} · 이번 카드만 선택`,
    scheduleSheetFootnote: "설정에서 기본값을 바꿀 수 있어요",
    trustTitle: "실행 확인 수준",
    trustHint: "익숙해질수록 확인은 줄고 실행은 빨라져요 · 언제든 바꿀 수 있어요",
    trustBadge: "적응형",
    trustSaved: "실행 확인 수준을 저장했습니다",
    trustStageActive: (stage: string) => `지금 단계: ${stage}`,
    trustScoreLine: (score: number) => `성공 경험 ${score}회`,
    trustNextMilestone: (remaining: number, label: string) =>
      `${remaining}회 더하면 ${label}`,
    trustActive: (label: string) => `선택: ${label}`,
    mapSheetTitle: "어떤 지도로 열까요?",
    mapSheetHint: (place: string) => `${place} · 앱을 골라 주세요`,
    mapBadge: "기본값",
    mapSheetFootnote: "다음부터는 기본 지도로 바로 열어요",
    navSectorTitle: "어디로 갈까요?",
    navSectorHint: (place: string) => `${place} · 내비 앱을 골라 주세요`,
    navSectorFootnote: "자주 쓰는 앱이 위로 올라가요 · 안 쓰는 앱은 점점 숨겨져요",
    navSectorFrequentBadge: "자주 씀",
    navSectorHide: "숨기기",
    integrationsTitle: "서비스 연결",
    integrationsHint: "Slack·Notion OAuth 또는 내 API 키를 연결해 Action 맥락에 씁니다",
    integrationsHintShort: "연결된 서비스만 표시됩니다",
    integrationsBadge: "연동",
    integrationsConnected: "연결됨",
    integrationsDisconnect: "연결 해제",
    integrationsOAuthConnect: "계정 연결",
    integrationsOAuthFallback: "OAuth 미설정 · 아래 토큰으로 연결",
    integrationsOAuthSection: "계정 OAuth",
    integrationsApiKeySection: "API 키",
    integrationsKeyConnect: "API 키 연결",
    integrationsKeyReplace: "키 변경",
    integrationsKeySave: "저장",
    integrationsTokenSave: "토큰 저장",
    integrationsSaving: "저장 중…",
    integrationsSaved: "연결 정보를 저장했습니다",
    integrationsSaveFail: "저장에 실패했습니다",
    integrationsKeyMissing: "키를 입력해 주세요",
    integrationsGuestNote:
      "로그인 전에는 이 기기에만 저장됩니다 · Google 로그인 후 계정에 안전하게 보관돼요",
    integrationsCloudNote: "연결 정보는 계정에 암호화 저장됩니다",
    integrationsLoading: "연결 상태 불러오는 중…",
    integrationsFootnote: "키는 서버에 암호화 저장 · day-start·보조 Action에 사용됩니다",
    integrationsOAuthSuccess: (provider: string) => `${provider} 연결 완료`,
    integrationsLoginRequired: "OAuth 연결은 먼저 Google 로그인이 필요해요",
    integrationsOAuthFail: "OAuth 연결에 실패했습니다",
  },
  welcome: {
    headline: RIMVIO.northStar,
    northStar: RIMVIO.northStarKo,
    body: `${RIMVIO.name}는 대화가 아니라 `,
    bodyStrong: "실행",
    bodyEnd: "입니다. 말·링크·사진을 Action Dock으로 바꿔 드립니다",
    pwaOk: "홈 화면에 추가되어 실행 중입니다",
    privacyTitle: "개인정보 · 입력 분석",
    privacyBody:
      "실행 버튼을 만들기 위해 공유·입력한 내용만 살짝 살펴봅니다. 로그인 없이도 이용하실 수 있고, 데이터는 이 기기에 남습니다",
    privacyLoginNote: "Google로 시작하시면 실행 기록이 계정과 함께합니다",
    privacyLink: "개인정보 안내",
    openFeed: "실행 화면 열기",
    addLink: "링크로 시작하기",
    androidSection: "Android · 공유로 추가하기",
    androidStep1Title: `${RIMVIO.name} 설치`,
    androidStep1Body: "Chrome 메뉴 → 홈 화면에 추가 또는 아래 설치 버튼",
    androidStep2Title: "다른 앱에서 공유",
    androidStep2Body: (brand: string) =>
      `YouTube·카톡 등 → 공유 → ${brand} 선택`,
    androidStep3Title: "넘기며 보기",
    androidStep3Body:
      "피드에서 위아래로 넘기고, ← 밀면 함께하기 · → 밀면 삭제 (3초 안 되돌리기)",
    iosSection: "iPhone · 붙여넣기로 추가하기",
    iosStep1Title: "홈 화면에 추가",
    iosStep1Body: "Safari 공유 → 홈 화면에 추가",
    iosStep2Title: "링크 복사",
    iosStep2Body: "카톡·Safari에서 링크 복사",
    iosStep3Body: "에 붙여넣기 → Action Dock으로 이어집니다",
    desktopSection: "데스크톱",
    desktopMid: "에 링크를 붙여넣거나",
    desktopEnd: "로 Experience OS를 체험해 보세요",
    tryDemo: "체험하기",
  },
  manual: {
    eyebrow: "사용 설명서",
    title: "림비오는 이렇게 씁니다",
    summary:
      "챗봇이 아니라 실행 OS예요. 말·링크·사진을 보내면 바로 할 수 있는 버튼(칩)이 뜨고, @로 원하는 앱 기능을 바로 불러옵니다.",
    step1Title: "1. 말하거나 붙여넣기",
    step1Body:
      "실행 화면 아래 입력창에 일정·주소·링크·사진을 보내세요. 유튜브·카톡에서 공유해도 됩니다.",
    step2Title: "2. @ 로 앱 기능 호출",
    step2Body:
      "채팅에 @네비, @타이머, @송금처럼 입력하면 해당 기능 칩이 대화 안에 붙습니다. @ = 앱 단축키라고 생각하면 돼요.",
    step3Title: "3. 칩을 눌러 실행",
    step3Body:
      "뜬 칩을 탭하면 카카오맵·토스·배민 등 연결된 앱으로 바로 이어집니다. 확인 없이 빠르게 실행할 수도 있어요.",
    mentionsTitle: "자주 쓰는 @ 예시",
    mentionsHint: "입력창에 @ 를 치면 더 많은 기능이 나와요",
    mentionsMore: "전체 목록은 채팅에 @설명서 입력 · @날씨, @환율, @QR, @번역 등 20개 이상",
    calendarTitle: "캘린더",
    calendarBody: "일정을 말하거나 링크에 시간을 정하면 타임라인에 쌓여요. 헤더 📅 아이콘으로 확인합니다.",
    poolTitle: "리소스풀",
    poolBody: "메모·링크·사진을 저장소에 모아둡니다. @메모 로 저장하거나 헤더 📁 아이콘으로 열어요.",
    tagline: "대화가 아니라 실행 — 말한 것을 바로 행동으로 바꿉니다.",
    tryCta: "실행 화면에서 바로 써보기",
    introTitle: "처음이시면 설명서부터 읽어보세요",
    introBody:
      "림비오는 챗봇이 아니라 실행 OS예요. 1분만 읽으면 @호출·칩 실행·피드·대화·관계 버블을 바로 쓸 수 있어요.",
    readManualCta: "설명서 읽기",
    skipIntroCta: "바로 써볼게요",
    feedBannerText: "아직 설명서를 안 읽으셨어요.",
    dismissBanner: "배너 닫기",
    settingsLink: "Rimvio 쓰는 법",
  },
  action: {
    emptyPrompt: "무엇을 도와드릴까요?",
    emptyHint: "말만 해 주세요. 찾고, 정리하고, 실행까지 이어드릴게요.",
    emptyNoSelection: "아래에 말을 걸거나, 링크·사진을 보내 보세요.",
    todayEmpty: "진행 중인 프로젝트가 없어요. 말을 걸면 Action Dock이 생깁니다.",
    streamEmpty: "일정을 말하거나 링크에 시간을 정하면 여기에 쌓여요.",
    streamLabel: "Timeline",
    openLink: "링크 열기",
  },
  comments: {
    done: "완료",
    coupon: "쿠폰",
    note: "메모",
    chat: "말하기",
    couponPreset: "할인 쿠폰 여기 있습니다",
    notePreset: "이것도 참고해 보세요",
    priceSnap: "가격 스냅",
    priceOk: "괜찮아요",
    priceHigh: "다소 비싸요",
  },
  priceVote: {
    title: "이 가격, 어떻게 생각하세요?",
    hintWithPrice: (price: string) => `지금 ${price} — 함께 확인해 보세요`,
    hintNoPrice: "가격 스냅을 찍고 👍👎로 의견을 남겨 주세요",
    snapButton: "가격 스냅",
    okButton: "괜찮아요",
    highButton: "다소 비싸요",
    okMessage: "이 가격은 괜찮은 것 같아요",
    highMessage: "조금 비싼 것 같아요",
    snapSaved: "가격 스냅을 저장했습니다",
    noPriceHint: "제목에서 가격을 찾지 못했습니다 — 메모로 남겨 주세요",
    inlineTitle: (price: string) => `${price}, 이 가격 어떠세요?`,
    inlineTitleFallback: "가격 함께 보기",
  },
  nextLink: {
    title: "다음은 이 링크는 어떠세요?",
    open: "열기",
    roomDone: "다음 링크로 넘어갑니다",
  },
  behavior: {
    doneButton: "완료",
    doneRelease: "하나 마무리하셨습니다",
    doneReleaseHint: "오늘 완료 목록에 추가되었습니다",
    foggCopied: (text: string) => `"${text}" 복사 — 바로 실행하세요`,
  },
  remind: {
    scheduled: (when: string) => `${when}에 다시 알려 드릴게요`,
    calendarOpened: (when: string) => `${when} · Google Calendar에서 저장해 주세요`,
    copiedSchedule: (when: string) => `${when} 예약 문구를 복사했어요`,
    kakaoCopied: "카카오톡에 붙여넣을 문구를 복사했습니다",
  },
  actions: {
    openOriginal: "원본 페이지 열기",
    openLink: "열기",
    referenceLink: "참고 링크 열기",
    translateRead: "번역해서 읽기",
    summary3: "3줄 요약",
    askAi: "AI에게 물어보기",
  },
  routing: {
    fallbackPrompt: "어떤 액션을 원하시나요?",
    fallbackHint: "선택",
    modeCommerce: "쇼핑·최저가",
    modeNews: "뉴스·요약",
    modeOpen: "그냥 열기",
  },
  archive: {
    subtitle: "잠시 쉬어 가는 링크",
  },
  app: {
    tagline: RIMVIO.tagline,
    loadingTitle: "잠시만 기다려 주세요",
    loadingSubtitle: "링크에서 할 일을 찾는 중…",
  },
  common: {
    close: "닫기",
    more: "더 보기",
    me: "나",
    tryAgain: "다시 시도해 주세요",
  },
};

export function openOriginalLabel() {
  return copy.actions.openOriginal;
}
