import {
  buildAmazonSearchHref,
  buildBestBuySearchHref,
  buildBunjangSearchHref,
  buildDaangnSearchHref,
  buildDanawaSearchHref,
  buildDepopSearchHref,
  buildEbaySearchHref,
  buildFacebookMarketplaceSearchHref,
  buildGoogleShoppingSearchHref,
  buildJoongnaSearchHref,
  buildKakakuSearchHref,
  buildMercariSearchHref,
  buildMusinsaSearchHref,
  buildNaverShoppingSearchHref,
  buildPoshmarkSearchHref,
  buildRakumaSearchHref,
  buildYahooAuctionJpSearchHref,
} from "@/lib/markets/search-urls";
import type { CompareDestination, CompareDestinationId } from "@/lib/markets/types";

export const COMPARE_DESTINATIONS: Record<CompareDestinationId, CompareDestination> = {
  bunjang: {
    id: "bunjang",
    label: "⚡ 번개장터",
    shortLabel: "번개",
    domainPattern: /bunjang/i,
    buildHref: buildBunjangSearchHref,
  },
  joongna: {
    id: "joongna",
    label: "🛒 중고나라",
    shortLabel: "중고나라",
    domainPattern: /joongna|junggo/i,
    buildHref: buildJoongnaSearchHref,
  },
  daangn: {
    id: "daangn",
    label: "🥕 당근",
    shortLabel: "당근",
    domainPattern: /daangn|karrot/i,
    buildHref: buildDaangnSearchHref,
  },
  danawa: {
    id: "danawa",
    label: "💰 다나와",
    shortLabel: "다나와",
    domainPattern: /danawa/i,
    buildHref: buildDanawaSearchHref,
  },
  naver_shopping: {
    id: "naver_shopping",
    label: "🛍 네이버 쇼핑",
    shortLabel: "네이버",
    domainPattern: /shopping\.naver|smartstore|naver\.com/i,
    buildHref: buildNaverShoppingSearchHref,
  },
  musinsa: {
    id: "musinsa",
    label: "👕 무신사",
    shortLabel: "무신사",
    domainPattern: /musinsa/i,
    buildHref: buildMusinsaSearchHref,
  },
  ebay: {
    id: "ebay",
    label: "🛒 eBay",
    shortLabel: "eBay",
    domainPattern: /ebay/i,
    buildHref: buildEbaySearchHref,
  },
  amazon: {
    id: "amazon",
    label: "📦 Amazon",
    shortLabel: "Amazon",
    domainPattern: /amazon\.(com|co\.uk)/i,
    buildHref: (query) => buildAmazonSearchHref(query, "www.amazon.com"),
  },
  facebook_marketplace: {
    id: "facebook_marketplace",
    label: "🏷 Facebook Marketplace",
    shortLabel: "Marketplace",
    domainPattern: /facebook\.com/i,
    buildHref: buildFacebookMarketplaceSearchHref,
  },
  google_shopping: {
    id: "google_shopping",
    label: "🔎 Google Shopping",
    shortLabel: "Shopping",
    domainPattern: /google\.com/i,
    buildHref: buildGoogleShoppingSearchHref,
  },
  bestbuy: {
    id: "bestbuy",
    label: "🖥 Best Buy",
    shortLabel: "Best Buy",
    domainPattern: /bestbuy/i,
    buildHref: buildBestBuySearchHref,
  },
  mercari: {
    id: "mercari",
    label: "📦 メルカリ",
    shortLabel: "Mercari",
    domainPattern: /mercari/i,
    buildHref: buildMercariSearchHref,
  },
  rakuma: {
    id: "rakuma",
    label: "👜 ラクマ",
    shortLabel: "Rakuma",
    domainPattern: /fril\.jp|rakuma/i,
    buildHref: buildRakumaSearchHref,
  },
  kakaku: {
    id: "kakaku",
    label: "💴 価格.com",
    shortLabel: "価格.com",
    domainPattern: /kakaku/i,
    buildHref: buildKakakuSearchHref,
  },
  amazon_jp: {
    id: "amazon_jp",
    label: "📦 Amazon JP",
    shortLabel: "Amazon",
    domainPattern: /amazon\.co\.jp/i,
    buildHref: (query) => buildAmazonSearchHref(query, "www.amazon.co.jp"),
  },
  yahoo_auction_jp: {
    id: "yahoo_auction_jp",
    label: "🔨 Yahoo!オークション",
    shortLabel: "Yahoo",
    domainPattern: /auctions\.yahoo\.co\.jp|yahoo\.co\.jp/i,
    buildHref: buildYahooAuctionJpSearchHref,
  },
  poshmark: {
    id: "poshmark",
    label: "👗 Poshmark",
    shortLabel: "Poshmark",
    domainPattern: /poshmark/i,
    buildHref: buildPoshmarkSearchHref,
  },
  depop: {
    id: "depop",
    label: "👕 Depop",
    shortLabel: "Depop",
    domainPattern: /depop/i,
    buildHref: buildDepopSearchHref,
  },
};

export function destinationById(id: CompareDestinationId) {
  return COMPARE_DESTINATIONS[id];
}
