import type { UnifiedStressCase } from "@/lib/testing/unified-stress/types";

export const UNIFIED_STRESS_CASES: UnifiedStressCase[] = [
  {
    id: "US-01-food",
    label: "Food decision with domain",
    input: "오늘 뭐 먹지?",
    expectedRouting: "FOOD",
    expectedAbstraction: "L2",
    tags: ["intent", "food"],
  },
  {
    id: "US-02-boundary",
    label: "L1 boundary — must ask",
    input: "뭐하지",
    expectedRouting: "DECISION",
    expectedAbstraction: "L1",
    tags: ["abstraction", "boundary"],
  },
  {
    id: "US-03-schedule-conflict",
    label: "Exercise vs existing meeting",
    input: "오늘 저녁 운동 가도 돼?",
    expectedRouting: "CALENDAR",
    expectedAbstraction: "L2",
    existingSchedule: [
      { time: "18:00", task: "팀 회의" },
      { time: "19:30", task: "약속" },
    ],
    proposedSchedule: [{ time: "18:00", task: "헬스 운동" }],
    tags: ["schedule", "conflict"],
  },
  {
    id: "US-04-multi-intent",
    label: "Food + schedule + money conflict",
    input: "배고픈데 일정도 있고 돈도 없어",
    expectedRouting: "FOOD",
    expectedAbstraction: "L2",
    tags: ["adversarial", "multi_intent"],
  },
  {
    id: "US-05-decision",
    label: "Purchase decision",
    input: "이거 사도 돼?",
    expectedRouting: "DECISION",
    expectedAbstraction: "L2",
    tags: ["decision"],
  },
  {
    id: "US-06-context-drift",
    label: "Context drift after food",
    input: "그거 추천해줘",
    history: [{ role: "user", content: "근처 맛집 추천" }],
    expectedRouting: "FOOD",
    expectedAbstraction: "L1",
    tags: ["context_drift"],
  },
  {
    id: "US-07-l4-system",
    label: "L4 system design",
    input: "수능 공부 루틴 장기 전략 짜줘",
    expectedRouting: "CALENDAR",
    expectedAbstraction: "L4",
    tags: ["abstraction", "planning"],
  },
  {
    id: "US-08-emotion",
    label: "Emotional reflection",
    input: "너무 힘들어",
    expectedRouting: "SOCIAL",
    expectedAbstraction: "L1",
    tags: ["emotion"],
  },
  {
    id: "US-09-health",
    label: "Health + exercise expansion",
    input: "다이어트 시작하려는데 운동 뭐하지",
    expectedRouting: "DECISION",
    expectedAbstraction: "L2",
    tags: ["health", "exercise"],
  },
  {
    id: "US-10-work-money",
    label: "Work + money optimization",
    input: "이직 준비하면서 월세 예산 줄이는 방법",
    expectedRouting: "DECISION",
    expectedAbstraction: "L3",
    tags: ["work", "money"],
  },
];
